# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allelesimCvec <- function(mu = 0, nu = 0, m = 0, wAA = 1, wAa = 0.75, waa = 0.5, p0 = 0.5, psource = 0.1, Fi = 0, d = 0, N = 100L, tmax = 10L) {
    .Call('popgensim_allelesimCvec', PACKAGE = 'popgensim', mu, nu, m, wAA, wAa, waa, p0, psource, Fi, d, N, tmax)
}

allelesimCmat <- function(mu = 0, nu = 0, m = 0, wAA = 1, wAa = 0.75, waa = 0.5, p0 = 0.5, psource = 0.1, Fi = 0, d = 0, N = 100L, tmax = 10L, rep = 10L) {
    .Call('popgensim_allelesimCmat', PACKAGE = 'popgensim', mu, nu, m, wAA, wAa, waa, p0, psource, Fi, d, N, tmax, rep)
}

rowSumsC <- function(x) {
    .Call('popgensim_rowSumsC', PACKAGE = 'popgensim', x)
}

