# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowSumsC <- function(x) {
    .Call('_nap_rowSumsC', PACKAGE = 'nap', x)
}

allelesimCvec <- function(mu = 0, nu = 0, m = 0, wAA = 1, wAa = 0.75, waa = 0.5, p0 = 0.5, psource = 0.1, Fi = 0, d = 0, N = 100L, tmax = 10L) {
    .Call('_nap_allelesimCvec', PACKAGE = 'nap', mu, nu, m, wAA, wAa, waa, p0, psource, Fi, d, N, tmax)
}

allelesimCmat <- function(mu = 0, nu = 0, m = 0, wAA = 1, wAa = 0.75, waa = 0.5, p0 = 0.5, psource = 0.1, Fi = 0, d = 0, N = 100L, tmax = 10L, rep = 10L) {
    .Call('_nap_allelesimCmat', PACKAGE = 'nap', mu, nu, m, wAA, wAa, waa, p0, psource, Fi, d, N, tmax, rep)
}

sample_num <- function(x, size, replace, prob = as.numeric( c())) {
    .Call('_nap_sample_num', PACKAGE = 'nap', x, size, replace, prob)
}

BMsubset <- function(A, myrows, mycols) {
    .Call('_nap_BMsubset', PACKAGE = 'nap', A, myrows, mycols)
}

upperTmat <- function(mat) {
    .Call('_nap_upperTmat', PACKAGE = 'nap', mat)
}

Xmvcenter <- function(X) {
    .Call('_nap_Xmvcenter', PACKAGE = 'nap', X)
}

LDrelative <- function(A, m, debug = FALSE) {
    .Call('_nap_LDrelative', PACKAGE = 'nap', A, m, debug)
}

runif_reflect <- function(minhere, maxhere, min, max) {
    .Call('_nap_runif_reflect', PACKAGE = 'nap', minhere, maxhere, min, max)
}

test_GPROPOSAL <- function(b = 1, a = 1, p = 1, mu = 1, epi = 1, svar = 1, ss = 0.1, bw = 0.5, iter = 1000L, verbose = FALSE, nupdates = 7L) {
    .Call('_nap_test_GPROPOSAL', PACKAGE = 'nap', b, a, p, mu, epi, svar, ss, bw, iter, verbose, nupdates)
}

PropoS <- function(nupdates = 1L, svar = 0.5) {
    .Call('_nap_PropoS', PACKAGE = 'nap', nupdates, svar)
}

test_SPROPOSAL <- function(nupdates = 1L, svar = 0.5, m = 3L, iter = 3000L, mode = 3L) {
    .Call('_nap_test_SPROPOSAL', PACKAGE = 'nap', nupdates, svar, m, iter, mode)
}

test_PRIOR <- function(s, min = -1, max = 10, mean = 0, svar = 0.5, sparsity = 0.1, mode = 1L) {
    .Call('_nap_test_PRIOR', PACKAGE = 'nap', s, min, max, mean, svar, sparsity, mode)
}

whichS <- function(s1, s2) {
    .Call('_nap_whichS', PACKAGE = 'nap', s1, s2)
}

W_go <- function(X, s, mode, epi = 1, verbose = FALSE) {
    .Call('_nap_W_go', PACKAGE = 'nap', X, s, mode, epi, verbose)
}

W_update <- function(X, s, mode, w, epi = 1, verbose = FALSE) {
    .Call('_nap_W_update', PACKAGE = 'nap', X, s, mode, w, epi, verbose)
}

